### ISSUE TITLE
Error running vignette example

### ISSUE THREAD

**Issue by aldojongejan** [oliviaAB/sismonr#2]
Thanks for making this interesting package!
I have tried to run the example code provided by the vignette, but stumbled upon an error. Could you help me out?

I have installed the development version of sismonr (but also the stable release throws the error).
As you can see, I've installed Julia (and am working on a Windows 10 machine)

library(sismonr)
findJuliaNoError(test = FALSE)
[1] "D:\\programs\\Julia-1.3.1\\bin\\julia.exe"
> #[1] "D:\\programs\\Julia-1.3.1\\bin\\julia.exe"
> 
> # Example code from vignette
> mysystem = createInSilicoSystem(G = 5, regcomplexes = "none", ploidy = 2)

> mypop = createInSilicoPopulation(1, mysystem)
> sim = simulateInSilicoSystem(mysystem, mypop, simtime = 1000, ntrials = 10)
Generating the stochastic system...
Done.

Starting simulations at 2020-01-24 09:49:17 CET

  |                                                                                                                                          |   0%Error: Evaluating Julia expression: juliaStochasticSimulation(R_1_17, Dict{String, Any}( "GCN1" => Dict{String, Any}( "qtlTCrate" => [1.19273376297277,1.06017223512057,1.01428671837992,0.829643356491054,1.08346970478645], "qtlRDrate" => [1.16107827277504,0.93350432087794,1.00703876754249,1.08299960569415,1.08858947363929], "qtlTCregbind" => [1.18660258797122,1.0,1.0,0.988788701307379,1.2586043498073], "qtlRDregrate" => [0.948124976174567,1.03656481046872,1.0,0.946147874675215,0.982738978782378], "qtlactivity" => [1.0,1.0,1.13406979687668,0.86360993771847,1.0], "qtlTLrate" => [0.888001271735364,0.0,1.00383246243943,0.0,1.0], "qtlPDrate" => [0.930677002904333,0.0,1.0,0.0,0.96882634235485], "qtlTLregbind" => [0.917729425814567,0.0,0.776080000263329,0.0,1.0], "qtlPDregrate" => [0.997745888629773,0.0,1.04603479122641,0.0,0.910137324413348], "qtlPTMregrate" => [1.16740828222959,0.0,0.992016073849468,0.0,0.95784360229115] ), "GCN2" => Dict{String, Any}( "qtlTCrate" => [1.19273376297277,1.0,1

with kind regards,
Aldo Jongejan

sessionInfo()
R Under development (unstable) (2019-11-05 r77375)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sismonr_2.0.0  devtools_2.2.1 usethis_1.5.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        XRJulia_0.9.0     compiler_4.0.0    pillar_1.4.3      XR_0.7.2          prettyunits_1.1.0 remotes_2.1.0     tools_4.0.0      
 [9] zeallot_0.1.0     testthat_2.3.1    digest_0.6.23     pkgbuild_1.0.6    pkgload_1.0.2     lifecycle_0.1.0   gtable_0.3.0      jsonlite_1.6     
[17] memoise_1.1.0     tibble_2.1.3      pkgconfig_2.0.3   rlang_0.4.2       cli_2.0.1         rstudioapi_0.10   curl_4.3          stringr_1.4.0    
[25] withr_2.1.2       dplyr_0.8.3       vctrs_0.2.1       tictoc_1.0        desc_1.2.0        fs_1.3.1          grid_4.0.0        rprojroot_1.3-2  
[33] tidyselect_0.2.5  glue_1.3.1        R6_2.4.1          processx_3.4.1    fansi_0.4.1       sessioninfo_1.1.1 tidyr_1.0.0       ggplot2_3.2.1    
[41] purrr_0.3.3       callr_3.4.0       magrittr_1.5      scales_1.1.0      backports_1.1.5   ps_1.3.0          ellipsis_0.3.0    assertthat_0.2.1 
[49] colorspace_1.4-1  stringi_1.4.5     lazyeval_0.2.2    munsell_0.5.0     truncnorm_1.0-8   crayon_1.3.4

**Comment by oliviaAB** [comment]
Hey! Sorry about the delay, I'll look into it right now. I have tried the example on my Windows 10 with the CRAN version, and it works fine for me. The problem is that since the generation of the systems is completely stochastic, the created network will be different every time I run the code. Did you try running the example a second time? If it still doesn't work and if you don't mind, could you save the objects mysystem and mypop as a Rdata object so I can play with it and see what's the problem?
Thanks for trying the package!

**Comment by aldojongejan** [comment]
Hi,

Tried a couple of more times (also on MacOSX, just to see whether it was the platform), but to no avail.

Here are the RDS files for mypop and mysystem.

Thanks for looking into this!

Regards,
Aldo

**Comment by oliviaAB** [comment]
I figured out the cause of the error: You're using Julia 1.3.1 whereas I developed v2 of sismonr with julia 1.2 . There must be a change of syntax between the two versions. I'll correct that and release a new version of sismonr asap. Sorry for the inconvenience!

**Comment by oliviaAB** [comment]
Ok I figured out where the error comes from. Right after I released v2 on CRAN, the authors of the Julia package that I use for the simulations made a major change in their package. The latest sismonr version on Github - v2.0.1, commit #4d0ca8b - forces Julia to install a prior version of the module with which sismonr is compatible. It will solve the errors - until I update sismonr to work with the newer version of the package.

**Comment by oliviaAB** [comment]
I closed the issue but I'll actually keep it open until you are satisfied with the patch :) Let me know how it goes!

**Comment by aldojongejan** [comment]
Hi,

It is fine to close the issue ;-)
My thought were indeed also in this direction, but I hadn’t yet followed up on this hunch, so thank you for looking into this!

I will try the patch (but I have a lot of other things on my plate at the moment), but I believe it is solved satisfactory. I can always downgrade Julia and try…

Many thanks for looking into this!!

Aldo

**Comment by aldojongejan** [comment]
Hi Olivia,

Download the new version from GitHub and now it works! ;-)

Thanks a lot, I really appreciate the quick fix!

Regards,
Aldo
